server:
  port: 1989

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/authDetailsDB?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: angad@db
    driverClassName: com.mysql.cj.jdbc.Driver

management:
  tracing:
    sampling:
      probability: 1.0