server:
  port: 1991

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      authentication-database: admin
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:documentsDb}
      username: ${MONGODB_USER:angad}
      password: ${MONGODB_PASSWORD:angad@db}
      auto-index-creation: true
      write-concern: NORMAL

management:
  tracing:
    sampling:
      probability: 1.0