server:
  port: 1992

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:expensesDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:angad@db}
    driverClassName: org.postgresql.Driver

management:
  tracing:
    sampling:
      probability: 1.0