server:
  port: 1996

eureka:
  instance:
    client:
      register-with-eureka: false
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0