server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka-server/eureka/
